// `bun run install` — drop a `git-3d` executable on your PATH so you can run the
// visualizer inside any repository. Because git auto-discovers `git-<name>`
// executables as subcommands, this also makes `git 3d` work from any repo.
//
// The wrapper runs this example from its own directory (so the bunfig preload and
// node_modules resolve) while pointing it at the repo you invoked it from via
// GIT3D_REPO. It is idempotent and never fails the surrounding install.
import { chmodSync, mkdirSync, writeFileSync } from "node:fs"
import { join } from "node:path"

const exampleDirectory = import.meta.dir
const entry = join(exampleDirectory, "main.tsx")
const home = process.env.HOME ?? process.env.USERPROFILE ?? ""
// ~/.bun/bin is on PATH for everyone who installed bun, so it's the natural home
// for a bun-powered command.
const binDirectory = join(home, ".bun", "bin")
const target = join(binDirectory, "git-3d")

const wrapper = `#!/bin/sh
# git-3d — Gource-style 3D visualizer of a git repository (rune example).
# Generated by \`bun run install\` in examples/git-3d. Run \`git 3d\` or \`git-3d\`
# inside any repository; pass a path to point it elsewhere.
repo="\${1:-$PWD}"
cd "${exampleDirectory}" || exit 1
RUNE_COMPILED=1 GIT3D_REPO="$repo" exec bun "${entry}"
`

try {
  mkdirSync(binDirectory, { recursive: true })
  writeFileSync(target, wrapper, { mode: 0o755 })
  chmodSync(target, 0o755)
  console.log(`installed git-3d → ${target}`)
  console.log("run `git 3d` (or `git-3d`) inside any repository to visualize it.")
  const path = process.env.PATH ?? ""
  if (!path.split(":").includes(binDirectory)) {
    console.log(`note: ${binDirectory} is not on your PATH — add it to use the command.`)
  }
} catch (cause) {
  // Never break a surrounding `bun install`: just report and move on.
  console.warn(`git-3d: could not install wrapper (${String(cause)})`)
}
